language: elixir
elixir:
  - 1.5
  - 1.6
otp_release:
  - 18.2.1
  - 19
  - 20
matrix:
  exclude:
    - elixir: 1.2.6
      otp_release: 17.5
    - elixir: 1.3.1
      otp_release: 17.5
sudo: false # to use faster container based build environment
script:
  - mix test
