language: elixir
elixir:
  - 1.1.1
  - 1.2.6
  - 1.3.1
otp_release:
  - 17.5
  - 18.2.1
matrix:
  exclude:
    - elixir: 1.2.6
      otp_release: 17.5
    - elixir: 1.3.1
      otp_release: 17.5
  include:
    - elixir: 1.4.5
      otp_release: 20.3
    - elixir: 1.5.3
      otp_release: 20.3
    - elixir: 1.6.6
      otp_release: 20.3
    - elixir: 1.7.4
      otp_release: 22.2
    - elixir: 1.8.2
      otp_release: 22.2
    - elixir: 1.9.4
      otp_release: 22.2
    - elixir: 1.10.2
      opt_release: 22.2
sudo: false # to use faster container based build environment
script:
  - mix test
